version: "3"

volumes:
  redis:

services:
  server:
    image: "docker.io/openwrt/asu:alpine"
    build:
      context: ./
      dockerfile: Containerfile.alpine
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis/
    ports:
      - "0.0.0.0:8001:8000"
    depends_on:
      - redis
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - ./asu:/app/asu:rw
      - ./excluded_targets:/app/excluded_targets:ro

  worker:
    image: "docker.io/openwrt/asu:alpine"
    restart: unless-stopped
    command: rqworker --with-scheduler
    environment:
      - CONTAINER_HOST=unix://$CONTAINER_SOCK
      - REDIS_URL=redis://redis/
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
      - ./asu:/app/asu:rw
    depends_on:
      - redis

  redis:
    image: "docker.io/redis:alpine"
    restart: unless-stopped
    volumes:
      - redis:/data/:rw

  squid:
    image: "docker.io/squid:alpine"
    build:
      context: ./alpine/squid
      dockerfile: ./alpine/squid/Containerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:3128:3128"
    volumes:
      - ".squid.conf:/etc/squid/conf.d/snippet.conf:ro"
      - "./squid/:/var/spool/squid/:rw"
