apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    uid: ce8s54dfiboqod
    url: redis://redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: false
      #    secureJsonData:
      #      password: $PASSWORD

